server:
  port: 8100

#  ssl:
#    key-store: classpath:6016850_a.xjbok.com.p12
#    key-store-password: Q1t1gznf
#    key-store-type: PKCS12
#    key-alias: alias
#    enabled: true

spring:
  application:
    # 应用名称
    name: xwcloud-gateway
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
  cloud:
    # 使用 Naoos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 43.228.77.84:8848
#        username: nacos
#        password: nacos
#      config:
#        server-addr: 43.228.77.84:8848
#        username: nacos
#        password: nacos
    # 使用 Sentinel 作为熔断器
    sentinel:
      transport:
        dashboard: 43.228.77.84:8899 # Sentinel控制台地址
        port: 8898 #端口配置会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互
      # 服务启动直接建立心跳连接
      eager: true
      #sentinel数据源配置(从哪里获取限流规则)
      datasource:
        lk: # 流控
          nacos:
            #读取哪个命名空间的配置(要和上面的nacos.config.namespace配置一致，否则会读不到文件。如果默认public，则可以不写)
           # namespace: dev
            server-addr: 43.228.77.84:8848 # nacos服务地址
            #限流规则配置文件的名称
            dataId: xwcloud-gateway-sentinel-flow-limit
            groupId: xwcloud
            data-type: json
            rule-type: flow
        degrade: # 降级
          nacos:
            server-addr: 43.228.77.84:8848
            dataId: xwcloud-gateway-sentinel-degrade-rules
            groupId: xwcloud
            rule-type: degrade
            data-type: json
        system: # 系统保护
          nacos:
            server-addr: 43.228.77.84:8848
            dataId: xwcloud-gateway-sentinel-system-rules
            groupId: xwcloud
            rule-type: system
            data-type: json

    # 路由网关配置
    gateway:
      globalcors: #网关CORS跨域设置
        corsConfigurations:
          '[/**]': #gateway网关上所有的URI都应用下面的跨域设计
            allowed-credentials: true   #允许携带认证信息
            allowedOrigins: "*"         #允许所有来源进行跨域访问
            allowedHeaders: "*"         #允许跨域请求头里的head字段
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        - id: XWCLOUD-OAUTH
          uri: lb://xwcloud-oauth
          predicates:
            - Method=GET,POST,DELETE,PUT
            - Path=/xwcloud-oauth/**
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: XWCLOUD-SYS
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://xwcloud-sys
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Method=GET,POST,DELETE,PUT
            - Path=/xwcloud-sys/**

        - id: XWCLOUD-HOMESCHOOL
          uri: lb://xwcloud-homeschool
          predicates:
            - Method=GET,POST,DELETE,PUT
            - Path=/xwcloud-homeschool/**

        - id: XWCLOUD-STU
          uri: lb://xwcloud-stu
          predicates:
            - Method=GET,POST,DELETE,PUT
            - Path=/xwcloud-stu/**

        - id: XWCLOUD-ZSBM
          uri: lb://xwcloud-zsbm
          predicates:
            - Method=GET,POST,DELETE,PUT
            - Path=/xwcloud-zsbm/**

        - id: XWCLOUD-PKXK
          uri: lb://xwcloud-pkxk
          predicates:
            - Method=GET,POST,DELETE,PUT
            - Path=/xwcloud-pkxk/**

        - id: XWCLOUD-CAIWU
          uri: lb://xwcloud-caiwu
          predicates:
            - Method=GET,POST,DELETE,PUT
            - Path=/xwcloud-caiwu/**

        - id: XWCLOUD-WSC
          uri: lb://xwcloud-wsc
          predicates:
            - Method=GET,POST,DELETE,PUT
            - Path=/xwcloud-wsc/**

        - id: XWCLOUD-OA
          uri: lb://xwcloud-oa
          predicates:
            - Method=GET,POST,DELETE,PUT
            - Path=/xwcloud-oa/**

  datasource:
    dynamic:
      p6spy: true
      druid:
        filters: stat
      datasource:
        master:
          username: root
          password: 123456
          url: jdbc:mysql://43.228.77.84:3305/xjbdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
          #driver-class-name: com.mysql.cj.jdbc.Driver
          driver-class-name: com.mysql.jdbc.Driver
          druid: #这里可以重写默认值
            initial-size: 5
  zipkin: #链路追踪
    base-url: http://43.228.77.84:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
    sleuth:
      sampler:
        probability: 1.0 #采样的百分比


filters:
  # 熔断降级配置
  - name: Hystrix
    args:
      name : default
      fallbackUri: 'forward:/defaultfallback'  #降级回调接口
  # redis限流 ， filter名称必须是RequestRateLimiter
  - name: RequestRateLimiter
    args:
      # 使用SpEL名称引用Bean，与新建的RateLimiterConfig类中的bean的name相同
      key-resolver: '#{@remoteAddrKeyResolver}'
      # 每秒最大访问次数
      redis-rate-limiter.replenishRate: 20
      # 令牌桶最大容量
      redis-rate-limiter.burstCapacity: 100


# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true


# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug

# 自定义字属性
xw:
  # 网关忽略的URL
  ignore: /getVerificationCode,/Login,/webjars,/swagger-ui.html,/swagger-resources,/v2/api-docs,/doc.html,/captcha.jpg,/getJigouListData

